name: ci

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/web/**"
      - "apps/docs/**"
      - "packages/**"
      - ".github/workflows/**"

  push:
    branches:
      - ci/workflow
    paths:
      - ".github/workflows/**" #test workflow

concurrency:
  group: pr-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm run lint

      - name: build
        run: pnpm run build
